n1=int(input("Ingrese el primer numero: "))
n2=int(input("Ingrese el segundo numero: "))
n3=int(input("Ingrese el tercer numero: "))
lista=(n1,n2,n3)
print(f"El numero más grande es {max(lista)}")
print(f"El numero más pequeño es {min(lista)}")